### ISSUE TITLE
TCW 20: Bad link to 2nd Jenkins testing server?

### ISSUE THREAD

**Issue by ebeshero** [TEIC/Documentation#3]
Now that our Jenkins ecosystem has been shifting, it looks like we need to update links to Jenkins in the TCW documentation. For example, reviewing our documentation on how to test edits to the Guidelines in TCW 20, I notice that the second Jenkins server listed here just links to a login screen. What's a better URL to use here?

> Now we commit the change to git, and Jenkins will start building. The build should fail, and it does. If we now go to the Jenkins workspace on one of our two build servers:
> https://jenkins.tei-c.org/job/TEIP5-Test-dev/ws/P5/Test/
> https://jenkins2.tei-c.org/job/TEIP5-Test-dev/ws/P5/Test/
>

**Comment by martindholmes** [comment]
Hi there,

The second Jenkins is running a much newer version of Jenkins than the others, and the workspace for jobs no longer seems to be exposed through the web interface. It's not clear to me whether this is a bug:

https://issues.jenkins-ci.org/browse/JENKINS-56114?page=com.atlassian.jira.plugin.system.issuetabpanels%3Aall-tabpanel

or a feature:

https://jenkins.io/security/advisory/2018-12-05/#SECURITY-904

but before I start trying to work around it, I'd first like to consider whether this approach is what we should be recommending, or whether it's better to encourage people to use a docker instance to do their own builds. What's the current thinking on this?

**Comment by peterstadler** [comment]
The pages are back and we do not need any updates to TCW22 in this regard

**Comment by peterstadler** [comment]
Sorry, looked at the wrong links …

**Comment by peterstadler** [comment]
strange though because the mentioned issues only affect Jenkins' versions < 2.168 and the main TEI Jenkins is already above at 2.190.2 (as is the second Jenkins).

**Comment by martindholmes** [comment]
I just looked at my security config, and I don't have workspace browsing turned on for anonymous users; I presume that's the default, but maybe I was just being cautious. I've turned on workspace access. Closing.
