### ISSUE TITLE
typo in 30?

### ISSUE THREAD

**Issue by sydb** [TEIC/Documentation#7]
In the last paragraph of [TCW30](https://github.com/TEIC/Documentation/blob/d07ac6b43bb8f11cc15cbdd278a90bbfeab2b607/TCW/tcw30.xml#L92) we refer to the “TEI Council Bylaws”. Surely this is a typo for “TEI-Consortium Bylaws”, no?

**Comment by martinascholger** [comment]
corrected typo and added a link to the Bylaws, close with b4587a9
